language: python
branches:
  only:
  - master
env:
  global:
  - HUGO_VERSION="0.62.0"
  - AWS_S3_BUCKET_NAME="particule-frontend-static-site"
  - AWS_CLOUDFRONT_DISTRIBUTION_ID="E2BTLS675M5S4F"
install:
  - pip install awscli
script:
  - wget -qO- "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" | tar xvz
  - ls
  - ./hugo
after_success:
  - aws s3 sync public s3://${AWS_S3_BUCKET_NAME} --delete
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
