language: python
branches:
  only:
  - master
env:
  global:
  - HUGO_VERSION="0.62.0"
  - AWS_S3_BUCKET_NAME="particule-frontend-static-site"
  - AWS_CLOUDFRONT_DISTRIBUTION_ID="E2BTLS675M5S4F"
install:
- pip install awscli
script:
- wget -qO- "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
  | tar xvz
- ls
- "./hugo"
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then aws s3 sync public s3://${AWS_S3_BUCKET_NAME} --delete; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'; fi
notifications:
  slack:
    rooms:
      secure: joiEGbXtsnUtBlW0MPL1fcu4bMgT+G/fqooD5L9KHf5LoxiRloiG7ik7wzwt5AH6BnIBwa0+BcXHlmQ3U2p7rdFcfmH2FMvRjZD/7kKmkqNs0XnSbgcgdRqxkAKfqmmpzOucqvxm/Yo2IxVkyXo5nYydDLbY4iWt1T62SDUFYXFOQYRgUVcePT1zhqGoWN20s4cevPbatcAB+jV0cjn61B7KlZ723tvlBlp+HNWVpVWx2aHQV3mrIfo2sz3MenhvJ9yQr0QGIJt7NgEfXb2OogWViDlDlpHx+7st1chwwO7lZ+dO3v+gmRvZT/Hq361dm/NgOdRcdNZpgqgSXikIht4uT6TyoLjIsN9gxRcAW+VL6X8p9uA/Du+H6QW+bMqDzd66qs24apDAnmxDIUEo3AdNYFHJhUKrDP8ztYOCwaO7MsxID7sVWbLVR+firen/I1a/iKh3MOet1/WRutD14tFVLWBRfNVpUlGCCctS8RcbJMoanNq4/0i3SdzrhMxZHBZEt9yuMthTHCbKY+ce0AIqPc1BzgOsX9OPl04B1INMaXlZsn3KSwhUxgmKhwTMri6RceLVkDgqjqJTo5Fo2ibjw56X16PVUUmtlPyKovyH9k18R9mxzMDPmeMJ7CgzJh+ErtBC3FbnTOtNR+Wog8f2VQVcznyUtf8YRn8mX5o=
