baseURL = "https://dev.particule.io"
languageCode = "en-us"
title = "particule."
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = false
DefaultContentLanguage = "fr"

# Hugo 60.0 and after
# allow raw html into markdown files
[markup.goldmark.renderer]
unsafe= true

# Site Params
[params]
    logo = "images/logo.png"

    # Gestion des langues : FR / EN / NL / DE
    [[Params.listeLangues]]
    code = "fr"
    [[Params.listeLangues]]
    code = "en"

    # meta data
    author = "particule."
    description = "This is meta description"

############################# Plugins ##########################
# css plugins
    [[Params.plugins.css]]
    URL = "plugins/themify-icons/themify-icons.css"
    [[Params.plugins.css]]
    URL = "plugins/fontawesome/all.min.css"

############################# social icons ##########################
    [[Params.social_Icon]]
    icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
    link = "#"

    [[Params.social_Icon]]
    icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
    link = "#"

    [[Params.social_Icon]]
    icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
    link = "#"

    [[Params.social_Icon]]
    icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
    link = "#"

    [[Params.social_Icon]]
    icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
    link = "#"

    [[Params.social_Icon]]
    icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
    link = "#"


# Gestion des langues : FR / EN / NL / DE
[Languages]
    ############ 1 - Site en FRANCAIS
    [Languages.fr]
    weight = 1
    languageCode = "fr-fr"
    title = "Particule | Cloud Native Infrastructure"
    dateFormat = "2 January 2006"

    home = "Home"
    logo = "images/logo.png"
    logopreload = "images/logos/logopreload.png"
    menufixed = false

    footerDescription = "Particule vous accompagne dans vos projets Cloud Native avec une expertise pointue sur Kubernetes, Docker, Amazon Web Services et OpenStack"
    footerServiceTitle = "Services"
    footerQuicklinkTitle = "Liens"
    footerAboutTitle = "A Propos"
    footerSubscribeTitle = "Subscribe"

    # Hero Area Section
    [Languages.fr.params.hero]
        enable  = true
        heading = "We build Cloud Native infrastructure"
        description = "D'une application sur votre laptop vers une infrastructure scalable, définie par du code."
        button  = true
        btnText = "Let's scale"
        btnURL  = "#about"
        videoThumb = ""
        videoURL   = ""

    # About 2 Section
    [Languages.fr.params.aboutSm]
        enable  = true
        title   = "Particule, l'expertise Cloud Native"
        description = "Les fondations de Particule reposent sur les concepts du DevOps et du Cloud avec l'ambition de vous aider à naviguer dans un écosystème toujours plus grand et plus complexe. Nous mettons notre expertise à votre disposition pour vos projets."

    # Blog Section On Homepage
    [Languages.fr.params.blog]
        enable  = true
        topTitle= ""
        title   = "Blog."
        subtitle= ""

    # Contact Section
    [Languages.fr.params.contact]
        enable  = true
        topTitle= "On vous écoute !"
        title   = "Nous contacter."
        subtitle= ""
        address = "128 rue la Boétie, 75008, Paris"
        phone   = "+33 6 84 39 34 12"
        email   = "contact@particule.io"
        github = "https://github.com/particuleio"
        twitter = "https://twitter.com/particuleio"
        linkedin= "https://www.linkedin.com/company/particuleio/"
        mapLatitude = "48.870955"
        mapLongitude= "2.305982"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.fr.params.cta]
        enable  = false
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = ""
        subtitle= ""
        btnText = "Nous contacter."

    ############# 2 - Site en ENGLISH
    [Languages.en]
    weight = 2
    languageCode = "en-us"
    title = "Particule | Cloud Native Infrastructure"
    dateFormat = "January 2, 2006"

    home = "Home"
    logo = "images/logo.png"
    logopreload = "images/logos/logopreload.png"
    menufixed = false

    footerDescription = "Particule helps you get started into the Cloud Native world with a strong expertise on Kubernetes, Docker, Amazon Web Services and OpenStack"
    footerServiceTitle = "Service"
    footerQuicklinkTitle = "Quicklinks"
    footerAboutTitle = "About"
    footerSubscribeTitle = "Subscribe"

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "We build Cloud Native infrastructure"
        description = "From an application on your developers laptop to a scalable infrastructure, define as code"
        button  = true
        btnText = "Let's scale"
        btnURL  = "https://themefisher.com/"
        videoThumb = "images/iaas.png"
        videoURL   = ""

    [Languages.en.params.philosophy]
        enable  = true
        title   = "HELLO"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable  = true
        title   = "Particule, Cloud Native experts"
        description = "Particule is built with DevOps principle at its core. Our mission is to help you navigate the growing Cloud Native ecosystem. Our skills as a service for your projects."

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = true
        topTitle= ""
        title   = "Blog."
        subtitle= ""

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "Tell us about your project"
        title   = "Contact Us."
        subtitle= ""
        address = "128 rue la Boétie, 75008, Paris"
        phone   = "+33 6 84 39 34 12"
        email   = "contact@particule.io"
        github = "https://github.com/particuleio"
        twitter = "https://twitter.com/particuleio"
        linkedin= "https://www.linkedin.com/company/particuleio/"
        mapLatitude = "48.870955"
        mapLongitude= "2.305982"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = ""
        subtitle= ""
        btnText = "Contact Us."

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Blog"
        url     = "blog"
        weight  = 1
